In [14]:
from tdf_pool.race import Race
from tdf_pool.stage import Stage
from tdf_pool.cycling_calendar import get_calendar
from tdf_pool.score import score_stage, get_score_template

from datetime import date

In [15]:
calendar = get_calendar(2024)
tdf2024_entry= calendar.loc[calendar['Name']=='Tour de France'].iloc[0]

In [16]:
TOMMY_selection = ['VAN WILDER Ilan', 'GEE Derek', 'THOMAS Geraint', 'MOHORIČ Matej','MARTINEZ Lenny', 'CICCONE Giulio', 'JORGENSON Matteo', 'ALMEIDA João', 'GALL Felix', 'YATES Adam', 'AYUSO Juan']
# Geschke, Onley, Soler, Cort,
MY_selection = ['MOHORIČ Matej','ROGLIČ Primož', 'GROENEWEGEN Dylan', 'GALL Felix', 'MARTINEZ Lenny', 'AYUSO Juan', 'JORGENSON Matteo', 'ACKERMANN Pascal']
# Kragh Andersen, Geschke, Nielson Powless, Meintjes, Ackermann, Declerq, Turgis, Sivakov, Tobias Johannessen

In [26]:
tdf2024 = Race(tdf2024_entry['Name'], tdf2024_entry['Start'], tdf2024_entry['Type'], tdf2024_entry['PartialURL'])
stage = Stage("Tour de France", "", date(2024,7,2), 5, "race/tour-de-france/2024", overwrite=True)

In [27]:
score_template = get_score_template()
scores = score_stage(stage, score_template)

In [28]:
scores['Rider'].unique()

array(['CAVENDISH Mark', 'PHILIPSEN Jasper', 'GIRMAY Biniam',
       'KRISTOFF Alexander', 'DE LIE Arnaud', 'JAKOBSEN Fabio',
       'ACKERMANN Pascal', 'GAVIRIA Fernando', 'DÉMARE Arnaud',
       'THIJSSEN Gerben', 'COQUARD Bryan', 'POGAČAR Tadej',
       'VAN DEN BERG Marijn', 'EVENEPOEL Remco', 'GROENEWEGEN Dylan',
       'ABRAHAMSEN Jonas', 'BENNETT Sam', 'TURGIS Anthony',
       'PEDERSEN Mads', 'AYUSO Juan', 'BISSEGGER Stefan',
       'VINGEGAARD Jonas', 'BEULLENS Cedric', 'VERCHER Mattéo',
       'TEUNISSEN Mike', 'RODRÍGUEZ Carlos', 'GIBBONS Ryan',
       'ROGLIČ Primož', 'VAUQUELIN Kévin', 'RUSSO Clément', 'ZINGLE Axel',
       'WÆRENSKJOLD Søren', 'LANDA Mikel', 'MADOUAS Valentin',
       'ALMEIDA João', 'WRIGHT Fred', 'CICCONE Giulio', 'BAUHAUS Phil',
       'JORGENSON Matteo', 'PAGE Hugo', 'BUITRAGO Santiago',
       'BERNAL Egan'], dtype=object)

In [29]:
scores.loc[scores['Rider'].isin(TOMMY_selection)]

,Rider,Team,Stage,RedLantern,GC,KOM,Sprint,Youth,IntermediateSprint,IntermediateKOM,Total
3,AYUSO Juan,UAE Team Emirates,0.0,0.0,7.0,0.0,0.0,4.0,0.0,0.0,11.0
2,ALMEIDA João,UAE Team Emirates,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0
11,CICCONE Giulio,Lidl - Trek,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
21,JORGENSON Matteo,Team Visma | Lease a Bike,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0

In [30]:
scores.loc[scores['Rider'].isin(TOMMY_selection)]['Total'].sum()

18.0

In [31]:
scores.loc[scores['Rider'].isin(MY_selection)]

,Rider,Team,Stage,RedLantern,GC,KOM,Sprint,Youth,IntermediateSprint,IntermediateKOM,Total
1,ACKERMANN Pascal,Israel - Premier Tech,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
19,GROENEWEGEN Dylan,Team Jayco AlUla,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0
3,AYUSO Juan,UAE Team Emirates,0.0,0.0,7.0,0.0,0.0,4.0,0.0,0.0,11.0
30,ROGLIČ Primož,Red Bull - BORA - hansgrohe,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,6.0
21,JORGENSON Matteo,Team Visma | Lease a Bike,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0

In [32]:
scores.loc[scores['Rider'].isin(MY_selection)]['Total'].sum()

53.0

Etappe 3 zou ik 40 punten moeten halen met de etape uitslag, 4 door het jeugdclassement en 1 van de rode lantaren. 45 in totaal. Maar heb er maar 38 gekregen.